version: '3.4'

networks:
  productifyapp:

services:
  productifydb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: productify-db
    environment:
      SA_PASSWORD: "password@12345#"
      ACCEPT_EULA: "Y"
    ports:
      - "8002:1433"
    networks:
      - productifyapp

  productifyapi:
    container_name: productify-api
    image: ${DOCKER_REGISTRY-}productify
    build:
      context: .
      dockerfile: productify/Dockerfile
    depends_on:
      - productifydb
    environment:
        - DB_HOST=productifydb
        - DB_NAME=Productify   
        - DB_SA_PASSWORD=password@12345#
    networks:
      - productifyapp