version: '3.4'

networks:
  productifyapp:

services:
  productifydb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: productify-db
    environment:
      SA_PASSWORD: "password@12345#"
      ACCEPT_EULA: "Y"
    ports:
      - "8002:1433"
    networks:
      - productifyapp

  productifyback:
    container_name: productify-back
    image: ${DOCKER_REGISTRY-}productify-back
    build:
      context: .
      dockerfile: productify-back/Dockerfile
    depends_on:
      - productifydb
    environment:
        - DB_HOST=productifydb
        - DB_NAME=Productify   
        - DB_SA_PASSWORD=password@12345#
        - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"
    networks:
      - productifyapp